'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_Support

    '''<summary>
    '''lnkbtn_RaiseRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtn_RaiseRequest As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnkbtn_PendingReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtn_PendingReport As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lnkbtn_CloseReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtn_CloseReport As Global.System.Web.UI.WebControls.ImageButton
End Class
